version: '3.8'
services:
  ollama-sqlcoder:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "ollama serve &
      sleep 5
      ollama pull sqlcoder:15b-q8_0
      wait"

  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=<API Key>
    volumes:
      - .:/app
    networks:
      - app-network

  streamlit:
    build:
      context: ./ui                    # points at ui/ folder
      dockerfile: Dockerfile           # ui/Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - fastapi-app  # Ensure Streamlit waits for FastAPI to be up
    networks:
      - app-network
      
volumes:
  ollama_data:

networks:
  app-network:  # Define the app-network
    driver: bridge